//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/error/v01")]
    public partial class BusinessRulesValidationExceptionType : ErrorBasedExceptionType
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InvalidParametersExceptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PermissionDeniedExceptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessRulesValidationExceptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CertificatePermissionDeniedExceptionType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/error/v01")]
    public partial class ErrorBasedExceptionType
    {
        
        private Error[] errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Error", Order=0)]
        public Error[] Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/error/v01")]
    public partial class Error
    {
        
        private string idField;
        
        private TextType messageField;
        
        private TextType fieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TextType Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TextType Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:21")]
    public partial class TextType
    {
        
        private string languageIDField;
        
        private string languageLocaleIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string languageID
        {
            get
            {
                return this.languageIDField;
            }
            set
            {
                this.languageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string languageLocaleID
        {
            get
            {
                return this.languageLocaleIDField;
            }
            set
            {
                this.languageLocaleIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/retrieval/v1")]
    public partial class AssociatedStatements
    {
        
        private string referenceNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string referenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public partial class ProducerType
    {
        
        private long positionField;
        
        private bool positionFieldSpecified;
        
        private string countryField;
        
        private string nameField;
        
        private byte[] geometryGeojsonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool positionSpecified
        {
            get
            {
                return this.positionFieldSpecified;
            }
            set
            {
                this.positionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] geometryGeojson
        {
            get
            {
                return this.geometryGeojsonField;
            }
            set
            {
                this.geometryGeojsonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public partial class SpeciesInformationType
    {
        
        private string scientificNameField;
        
        private string commonNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string scientificName
        {
            get
            {
                return this.scientificNameField;
            }
            set
            {
                this.scientificNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string commonName
        {
            get
            {
                return this.commonNameField;
            }
            set
            {
                this.commonNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public partial class GoodsMeasureType
    {
        
        private decimal volumeField;
        
        private bool volumeFieldSpecified;
        
        private decimal netWeightField;
        
        private bool netWeightFieldSpecified;
        
        private string supplementaryUnitField;
        
        private SupplementaryUnitQualifier supplementaryUnitQualifierField;
        
        private bool supplementaryUnitQualifierFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal volume
        {
            get
            {
                return this.volumeField;
            }
            set
            {
                this.volumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool volumeSpecified
        {
            get
            {
                return this.volumeFieldSpecified;
            }
            set
            {
                this.volumeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal netWeight
        {
            get
            {
                return this.netWeightField;
            }
            set
            {
                this.netWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool netWeightSpecified
        {
            get
            {
                return this.netWeightFieldSpecified;
            }
            set
            {
                this.netWeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=2)]
        public string supplementaryUnit
        {
            get
            {
                return this.supplementaryUnitField;
            }
            set
            {
                this.supplementaryUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SupplementaryUnitQualifier supplementaryUnitQualifier
        {
            get
            {
                return this.supplementaryUnitQualifierField;
            }
            set
            {
                this.supplementaryUnitQualifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool supplementaryUnitQualifierSpecified
        {
            get
            {
                return this.supplementaryUnitQualifierFieldSpecified;
            }
            set
            {
                this.supplementaryUnitQualifierFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public enum SupplementaryUnitQualifier
    {
        
        /// <remarks/>
        ASV,
        
        /// <remarks/>
        ASVX,
        
        /// <remarks/>
        CCT,
        
        /// <remarks/>
        CEN,
        
        /// <remarks/>
        CTM,
        
        /// <remarks/>
        DAP,
        
        /// <remarks/>
        DHS,
        
        /// <remarks/>
        DTN,
        
        /// <remarks/>
        DTNE,
        
        /// <remarks/>
        DTNF,
        
        /// <remarks/>
        DTNG,
        
        /// <remarks/>
        DTNL,
        
        /// <remarks/>
        DTNM,
        
        /// <remarks/>
        DTNR,
        
        /// <remarks/>
        DTNS,
        
        /// <remarks/>
        DTNZ,
        
        /// <remarks/>
        ENP,
        
        /// <remarks/>
        EUR,
        
        /// <remarks/>
        GFI,
        
        /// <remarks/>
        GRM,
        
        /// <remarks/>
        GRT,
        
        /// <remarks/>
        HLT,
        
        /// <remarks/>
        HMT,
        
        /// <remarks/>
        KAC,
        
        /// <remarks/>
        KCC,
        
        /// <remarks/>
        KCL,
        
        /// <remarks/>
        KGM,
        
        /// <remarks/>
        KGMA,
        
        /// <remarks/>
        KGME,
        
        /// <remarks/>
        KGMG,
        
        /// <remarks/>
        KGMP,
        
        /// <remarks/>
        KGMS,
        
        /// <remarks/>
        KGMT,
        
        /// <remarks/>
        KLT,
        
        /// <remarks/>
        KMA,
        
        /// <remarks/>
        KMT,
        
        /// <remarks/>
        KNI,
        
        /// <remarks/>
        KNS,
        
        /// <remarks/>
        KPH,
        
        /// <remarks/>
        KPO,
        
        /// <remarks/>
        KPP,
        
        /// <remarks/>
        KSD,
        
        /// <remarks/>
        KSH,
        
        /// <remarks/>
        KUR,
        
        /// <remarks/>
        LPA,
        
        /// <remarks/>
        LTR,
        
        /// <remarks/>
        LTRA,
        
        /// <remarks/>
        MIL,
        
        /// <remarks/>
        MPR,
        
        /// <remarks/>
        MTK,
        
        /// <remarks/>
        MTQ,
        
        /// <remarks/>
        MTQC,
        
        /// <remarks/>
        MTR,
        
        /// <remarks/>
        MWH,
        
        /// <remarks/>
        NAR,
        
        /// <remarks/>
        NARB,
        
        /// <remarks/>
        NCL,
        
        /// <remarks/>
        NPR,
        
        /// <remarks/>
        TJO,
        
        /// <remarks/>
        TNE,
        
        /// <remarks/>
        TNEE,
        
        /// <remarks/>
        TNEI,
        
        /// <remarks/>
        TNEJ,
        
        /// <remarks/>
        TNEK,
        
        /// <remarks/>
        TNEM,
        
        /// <remarks/>
        TNER,
        
        /// <remarks/>
        TNEZ,
        
        /// <remarks/>
        WAT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public partial class CommercialDescriptionType
    {
        
        private string descriptionOfGoodsField;
        
        private GoodsMeasureType goodsMeasureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string descriptionOfGoods
        {
            get
            {
                return this.descriptionOfGoodsField;
            }
            set
            {
                this.descriptionOfGoodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public GoodsMeasureType goodsMeasure
        {
            get
            {
                return this.goodsMeasureField;
            }
            set
            {
                this.goodsMeasureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public partial class CommodityType
    {
        
        private long positionField;
        
        private bool positionFieldSpecified;
        
        private CommercialDescriptionType descriptorsField;
        
        private string hsHeadingField;
        
        private SpeciesInformationType[] speciesInfoField;
        
        private ProducerType[] producersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool positionSpecified
        {
            get
            {
                return this.positionFieldSpecified;
            }
            set
            {
                this.positionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CommercialDescriptionType descriptors
        {
            get
            {
                return this.descriptorsField;
            }
            set
            {
                this.descriptorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string hsHeading
        {
            get
            {
                return this.hsHeadingField;
            }
            set
            {
                this.hsHeadingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("speciesInfo", Order=3)]
        public SpeciesInformationType[] speciesInfo
        {
            get
            {
                return this.speciesInfoField;
            }
            set
            {
                this.speciesInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("producers", Order=4)]
        public ProducerType[] producers
        {
            get
            {
                return this.producersField;
            }
            set
            {
                this.producersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public partial class operatorInfo
    {
        
        private string nameField;
        
        private string countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public partial class EventInfo
    {
        
        private DdsStatusType statusField;
        
        private bool statusFieldSpecified;
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string updatedByField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DdsStatusType status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified
        {
            get
            {
                return this.dateFieldSpecified;
            }
            set
            {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string updatedBy
        {
            get
            {
                return this.updatedByField;
            }
            set
            {
                this.updatedByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public enum DdsStatusType
    {
        
        /// <remarks/>
        AVAILABLE,
        
        /// <remarks/>
        SUBMITTED,
        
        /// <remarks/>
        REJECTED,
        
        /// <remarks/>
        CANCELLED,
        
        /// <remarks/>
        WITHDRAWN,
        
        /// <remarks/>
        ARCHIVED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/retrieval/v1")]
    public partial class SupplierStatement
    {
        
        private string referenceNumberField;
        
        private ActivityType activityTypeField;
        
        private EventInfo statusField;
        
        private operatorInfo operatorField;
        
        private CommodityType[] commoditiesField;
        
        private AssociatedStatements[] associateStatementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string referenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ActivityType activityType
        {
            get
            {
                return this.activityTypeField;
            }
            set
            {
                this.activityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public EventInfo status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public operatorInfo @operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("commodities", Order=4)]
        public CommodityType[] commodities
        {
            get
            {
                return this.commoditiesField;
            }
            set
            {
                this.commoditiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("associateStatement", Order=5)]
        public AssociatedStatements[] associateStatement
        {
            get
            {
                return this.associateStatementField;
            }
            set
            {
                this.associateStatementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public enum ActivityType
    {
        
        /// <remarks/>
        DOMESTIC,
        
        /// <remarks/>
        TRADE,
        
        /// <remarks/>
        IMPORT,
        
        /// <remarks/>
        EXPORT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/retrieval/v1")]
    public partial class GetStatementByIdentifiersResponse
    {
        
        private SupplierStatement statementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SupplierStatement statement
        {
            get
            {
                return this.statementField;
            }
            set
            {
                this.statementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/retrieval/v1")]
    public partial class GetStatementByIdentifiersRequest
    {
        
        private string referenceNumberField;
        
        private string verificationNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string referenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string verificationNumber
        {
            get
            {
                return this.verificationNumberField;
            }
            set
            {
                this.verificationNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/retrieval/v1")]
    public partial class StatementInfoType
    {
        
        private string identifierField;
        
        private string internalReferenceNumberField;
        
        private string referenceNumberField;
        
        private string verificationNumberField;
        
        private DdsStatusType statusField;
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string updatedByField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string internalReferenceNumber
        {
            get
            {
                return this.internalReferenceNumberField;
            }
            set
            {
                this.internalReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string referenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string verificationNumber
        {
            get
            {
                return this.verificationNumberField;
            }
            set
            {
                this.verificationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public DdsStatusType status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified
        {
            get
            {
                return this.dateFieldSpecified;
            }
            set
            {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string updatedBy
        {
            get
            {
                return this.updatedByField;
            }
            set
            {
                this.updatedByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/error/v01")]
    public partial class InvalidParametersExceptionType : ErrorBasedExceptionType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/error/v01")]
    public partial class PermissionDeniedExceptionType : ErrorBasedExceptionType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/error/v01")]
    public partial class CertificatePermissionDeniedExceptionType : ErrorBasedExceptionType
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/retrieval/v1", ConfigurationName="Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.EUDRRetrievalP" +
        "ort")]
    public interface EUDRRetrievalPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ec.europa.eu/tracesnt/certificate/eudr/retrieval/getDdsInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Error[]))]
        System.Threading.Tasks.Task<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementInfoResponse> getDdsInfoAsync(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ec.europa.eu/tracesnt/certificate/eudr/retrieval/getDdsInfoByInternalRefer" +
            "enceNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Error[]))]
        System.Threading.Tasks.Task<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetDdsInfoByInternalReferenceNumberResponse> getDdsInfoByInternalReferenceNumberAsync(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetDdsInfoByInternalReferenceNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ec.europa.eu/tracesnt/certificate/eudr/eudr4authorities/getStatementByIden" +
            "tifiers", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.BusinessRulesValidationExceptionType), Action="http://ec.europa.eu/tracesnt/certificate/eudr/eudr4authorities/getStatementByIden" +
            "tifiers", Name="BusinessRulesValidationException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Error[]))]
        System.Threading.Tasks.Task<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementByIdentifiersResponse1> getStatementByIdentifiersAsync(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementByIdentifiersRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatementInfoRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/base/v4")]
        public string WebServiceClientId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatementInfoRequest", Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/retrieval/v1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("identifier", IsNullable=false)]
        public string[] GetStatementInfoRequest1;
        
        public GetStatementInfoRequest()
        {
        }
        
        public GetStatementInfoRequest(string WebServiceClientId, string[] GetStatementInfoRequest1)
        {
            this.WebServiceClientId = WebServiceClientId;
            this.GetStatementInfoRequest1 = GetStatementInfoRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatementInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatementInfoResponse", Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/retrieval/v1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("statementInfo", IsNullable=false)]
        public Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.StatementInfoType[] GetStatementInfoResponse1;
        
        public GetStatementInfoResponse()
        {
        }
        
        public GetStatementInfoResponse(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.StatementInfoType[] GetStatementInfoResponse1)
        {
            this.GetStatementInfoResponse1 = GetStatementInfoResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDdsInfoByInternalReferenceNumberRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/base/v4")]
        public string WebServiceClientId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDdsInfoByInternalReferenceNumberRequest", Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/retrieval/v1", Order=0)]
        public string GetDdsInfoByInternalReferenceNumberRequest1;
        
        public GetDdsInfoByInternalReferenceNumberRequest()
        {
        }
        
        public GetDdsInfoByInternalReferenceNumberRequest(string WebServiceClientId, string GetDdsInfoByInternalReferenceNumberRequest1)
        {
            this.WebServiceClientId = WebServiceClientId;
            this.GetDdsInfoByInternalReferenceNumberRequest1 = GetDdsInfoByInternalReferenceNumberRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDdsInfoByInternalReferenceNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDdsInfoByInternalReferenceNumberResponse", Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/retrieval/v1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("statementInfo", IsNullable=false)]
        public Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.StatementInfoType[] GetDdsInfoByInternalReferenceNumberResponse1;
        
        public GetDdsInfoByInternalReferenceNumberResponse()
        {
        }
        
        public GetDdsInfoByInternalReferenceNumberResponse(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.StatementInfoType[] GetDdsInfoByInternalReferenceNumberResponse1)
        {
            this.GetDdsInfoByInternalReferenceNumberResponse1 = GetDdsInfoByInternalReferenceNumberResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatementByIdentifiersRequest1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/base/v4")]
        public string WebServiceClientId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/retrieval/v1", Order=0)]
        public Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementByIdentifiersRequest GetStatementByIdentifiersRequest;
        
        public GetStatementByIdentifiersRequest1()
        {
        }
        
        public GetStatementByIdentifiersRequest1(string WebServiceClientId, Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementByIdentifiersRequest GetStatementByIdentifiersRequest)
        {
            this.WebServiceClientId = WebServiceClientId;
            this.GetStatementByIdentifiersRequest = GetStatementByIdentifiersRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatementByIdentifiersResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/retrieval/v1", Order=0)]
        public Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementByIdentifiersResponse GetStatementByIdentifiersResponse;
        
        public GetStatementByIdentifiersResponse1()
        {
        }
        
        public GetStatementByIdentifiersResponse1(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementByIdentifiersResponse GetStatementByIdentifiersResponse)
        {
            this.GetStatementByIdentifiersResponse = GetStatementByIdentifiersResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface EUDRRetrievalPortChannel : Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.EUDRRetrievalPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class EUDRRetrievalPortClient : System.ServiceModel.ClientBase<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.EUDRRetrievalPort>, Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.EUDRRetrievalPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EUDRRetrievalPortClient() : 
                base(EUDRRetrievalPortClient.GetDefaultBinding(), EUDRRetrievalPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.EUDRRetrievalServiceV1Endpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EUDRRetrievalPortClient(EndpointConfiguration endpointConfiguration) : 
                base(EUDRRetrievalPortClient.GetBindingForEndpoint(endpointConfiguration), EUDRRetrievalPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EUDRRetrievalPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EUDRRetrievalPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EUDRRetrievalPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EUDRRetrievalPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EUDRRetrievalPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementInfoResponse> Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.EUDRRetrievalPort.getDdsInfoAsync(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementInfoRequest request)
        {
            return base.Channel.getDdsInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementInfoResponse> getDdsInfoAsync(string WebServiceClientId, string[] GetStatementInfoRequest1)
        {
            Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementInfoRequest inValue = new Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementInfoRequest();
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.GetStatementInfoRequest1 = GetStatementInfoRequest1;
            return ((Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.EUDRRetrievalPort)(this)).getDdsInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetDdsInfoByInternalReferenceNumberResponse> Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.EUDRRetrievalPort.getDdsInfoByInternalReferenceNumberAsync(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetDdsInfoByInternalReferenceNumberRequest request)
        {
            return base.Channel.getDdsInfoByInternalReferenceNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetDdsInfoByInternalReferenceNumberResponse> getDdsInfoByInternalReferenceNumberAsync(string WebServiceClientId, string GetDdsInfoByInternalReferenceNumberRequest1)
        {
            Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetDdsInfoByInternalReferenceNumberRequest inValue = new Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetDdsInfoByInternalReferenceNumberRequest();
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.GetDdsInfoByInternalReferenceNumberRequest1 = GetDdsInfoByInternalReferenceNumberRequest1;
            return ((Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.EUDRRetrievalPort)(this)).getDdsInfoByInternalReferenceNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementByIdentifiersResponse1> Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.EUDRRetrievalPort.getStatementByIdentifiersAsync(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementByIdentifiersRequest1 request)
        {
            return base.Channel.getStatementByIdentifiersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementByIdentifiersResponse1> getStatementByIdentifiersAsync(string WebServiceClientId, Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementByIdentifiersRequest GetStatementByIdentifiersRequest)
        {
            Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementByIdentifiersRequest1 inValue = new Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.GetStatementByIdentifiersRequest1();
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.GetStatementByIdentifiersRequest = GetStatementByIdentifiersRequest;
            return ((Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRRetrievalService.EUDRRetrievalPort)(this)).getStatementByIdentifiersAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EUDRRetrievalServiceV1Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EUDRRetrievalServiceV1Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://acceptance.eudr.webcloud.ec.europa.eu/tracesnt/ws/EUDRRetrievalServiceV1");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EUDRRetrievalPortClient.GetBindingForEndpoint(EndpointConfiguration.EUDRRetrievalServiceV1Endpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EUDRRetrievalPortClient.GetEndpointAddress(EndpointConfiguration.EUDRRetrievalServiceV1Endpoint);
        }
        
        public enum EndpointConfiguration
        {
            
            EUDRRetrievalServiceV1Endpoint,
        }
    }
}
