//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/error/v01")]
    public partial class BusinessRulesValidationExceptionType : ErrorBasedExceptionType
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InvalidParametersExceptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PermissionDeniedExceptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessRulesValidationExceptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CertificatePermissionDeniedExceptionType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/error/v01")]
    public partial class ErrorBasedExceptionType
    {
        
        private Error[] errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Error", Order=0)]
        public Error[] Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/error/v01")]
    public partial class Error
    {
        
        private string idField;
        
        private TextType messageField;
        
        private TextType fieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TextType Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TextType Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:21")]
    public partial class TextType
    {
        
        private string languageIDField;
        
        private string languageLocaleIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string languageID
        {
            get
            {
                return this.languageIDField;
            }
            set
            {
                this.languageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string languageLocaleID
        {
            get
            {
                return this.languageLocaleIDField;
            }
            set
            {
                this.languageLocaleIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/submission/v1")]
    public partial class SubmitStatementResponseType
    {
        
        private string ddsIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ddsIdentifier
        {
            get
            {
                return this.ddsIdentifierField;
            }
            set
            {
                this.ddsIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public partial class AssociatedStatementsType
    {
        
        private string referenceNumberField;
        
        private string verificationNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string referenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string verificationNumber
        {
            get
            {
                return this.verificationNumberField;
            }
            set
            {
                this.verificationNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public partial class ProducerType
    {
        
        private long positionField;
        
        private bool positionFieldSpecified;
        
        private string countryField;
        
        private string nameField;
        
        private byte[] geometryGeojsonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool positionSpecified
        {
            get
            {
                return this.positionFieldSpecified;
            }
            set
            {
                this.positionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] geometryGeojson
        {
            get
            {
                return this.geometryGeojsonField;
            }
            set
            {
                this.geometryGeojsonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public partial class SpeciesInformationType
    {
        
        private string scientificNameField;
        
        private string commonNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string scientificName
        {
            get
            {
                return this.scientificNameField;
            }
            set
            {
                this.scientificNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string commonName
        {
            get
            {
                return this.commonNameField;
            }
            set
            {
                this.commonNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public partial class GoodsMeasureType
    {
        
        private decimal volumeField;
        
        private bool volumeFieldSpecified;
        
        private decimal netWeightField;
        
        private bool netWeightFieldSpecified;
        
        private string supplementaryUnitField;
        
        private SupplementaryUnitQualifier supplementaryUnitQualifierField;
        
        private bool supplementaryUnitQualifierFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal volume
        {
            get
            {
                return this.volumeField;
            }
            set
            {
                this.volumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool volumeSpecified
        {
            get
            {
                return this.volumeFieldSpecified;
            }
            set
            {
                this.volumeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal netWeight
        {
            get
            {
                return this.netWeightField;
            }
            set
            {
                this.netWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool netWeightSpecified
        {
            get
            {
                return this.netWeightFieldSpecified;
            }
            set
            {
                this.netWeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=2)]
        public string supplementaryUnit
        {
            get
            {
                return this.supplementaryUnitField;
            }
            set
            {
                this.supplementaryUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SupplementaryUnitQualifier supplementaryUnitQualifier
        {
            get
            {
                return this.supplementaryUnitQualifierField;
            }
            set
            {
                this.supplementaryUnitQualifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool supplementaryUnitQualifierSpecified
        {
            get
            {
                return this.supplementaryUnitQualifierFieldSpecified;
            }
            set
            {
                this.supplementaryUnitQualifierFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public enum SupplementaryUnitQualifier
    {
        
        /// <remarks/>
        ASV,
        
        /// <remarks/>
        ASVX,
        
        /// <remarks/>
        CCT,
        
        /// <remarks/>
        CEN,
        
        /// <remarks/>
        CTM,
        
        /// <remarks/>
        DAP,
        
        /// <remarks/>
        DHS,
        
        /// <remarks/>
        DTN,
        
        /// <remarks/>
        DTNE,
        
        /// <remarks/>
        DTNF,
        
        /// <remarks/>
        DTNG,
        
        /// <remarks/>
        DTNL,
        
        /// <remarks/>
        DTNM,
        
        /// <remarks/>
        DTNR,
        
        /// <remarks/>
        DTNS,
        
        /// <remarks/>
        DTNZ,
        
        /// <remarks/>
        ENP,
        
        /// <remarks/>
        EUR,
        
        /// <remarks/>
        GFI,
        
        /// <remarks/>
        GRM,
        
        /// <remarks/>
        GRT,
        
        /// <remarks/>
        HLT,
        
        /// <remarks/>
        HMT,
        
        /// <remarks/>
        KAC,
        
        /// <remarks/>
        KCC,
        
        /// <remarks/>
        KCL,
        
        /// <remarks/>
        KGM,
        
        /// <remarks/>
        KGMA,
        
        /// <remarks/>
        KGME,
        
        /// <remarks/>
        KGMG,
        
        /// <remarks/>
        KGMP,
        
        /// <remarks/>
        KGMS,
        
        /// <remarks/>
        KGMT,
        
        /// <remarks/>
        KLT,
        
        /// <remarks/>
        KMA,
        
        /// <remarks/>
        KMT,
        
        /// <remarks/>
        KNI,
        
        /// <remarks/>
        KNS,
        
        /// <remarks/>
        KPH,
        
        /// <remarks/>
        KPO,
        
        /// <remarks/>
        KPP,
        
        /// <remarks/>
        KSD,
        
        /// <remarks/>
        KSH,
        
        /// <remarks/>
        KUR,
        
        /// <remarks/>
        LPA,
        
        /// <remarks/>
        LTR,
        
        /// <remarks/>
        LTRA,
        
        /// <remarks/>
        MIL,
        
        /// <remarks/>
        MPR,
        
        /// <remarks/>
        MTK,
        
        /// <remarks/>
        MTQ,
        
        /// <remarks/>
        MTQC,
        
        /// <remarks/>
        MTR,
        
        /// <remarks/>
        MWH,
        
        /// <remarks/>
        NAR,
        
        /// <remarks/>
        NARB,
        
        /// <remarks/>
        NCL,
        
        /// <remarks/>
        NPR,
        
        /// <remarks/>
        TJO,
        
        /// <remarks/>
        TNE,
        
        /// <remarks/>
        TNEE,
        
        /// <remarks/>
        TNEI,
        
        /// <remarks/>
        TNEJ,
        
        /// <remarks/>
        TNEK,
        
        /// <remarks/>
        TNEM,
        
        /// <remarks/>
        TNER,
        
        /// <remarks/>
        TNEZ,
        
        /// <remarks/>
        WAT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public partial class CommercialDescriptionType
    {
        
        private string descriptionOfGoodsField;
        
        private GoodsMeasureType goodsMeasureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string descriptionOfGoods
        {
            get
            {
                return this.descriptionOfGoodsField;
            }
            set
            {
                this.descriptionOfGoodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public GoodsMeasureType goodsMeasure
        {
            get
            {
                return this.goodsMeasureField;
            }
            set
            {
                this.goodsMeasureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public partial class CommodityType
    {
        
        private long positionField;
        
        private bool positionFieldSpecified;
        
        private CommercialDescriptionType descriptorsField;
        
        private string hsHeadingField;
        
        private SpeciesInformationType[] speciesInfoField;
        
        private ProducerType[] producersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool positionSpecified
        {
            get
            {
                return this.positionFieldSpecified;
            }
            set
            {
                this.positionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CommercialDescriptionType descriptors
        {
            get
            {
                return this.descriptorsField;
            }
            set
            {
                this.descriptorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string hsHeading
        {
            get
            {
                return this.hsHeadingField;
            }
            set
            {
                this.hsHeadingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("speciesInfo", Order=3)]
        public SpeciesInformationType[] speciesInfo
        {
            get
            {
                return this.speciesInfoField;
            }
            set
            {
                this.speciesInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("producers", Order=4)]
        public ProducerType[] producers
        {
            get
            {
                return this.producersField;
            }
            set
            {
                this.producersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/base/v4")]
    public partial class NameAndAddressType
    {
        
        private string nameField;
        
        private string countryField;
        
        private string streetField;
        
        private string postalCodeField;
        
        private string cityField;
        
        private string addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string postalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public partial class EconomicOperatorReferenceNumberType
    {
        
        private IdentifierTypeType identifierTypeField;
        
        private string identifierValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IdentifierTypeType identifierType
        {
            get
            {
                return this.identifierTypeField;
            }
            set
            {
                this.identifierTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string identifierValue
        {
            get
            {
                return this.identifierValueField;
            }
            set
            {
                this.identifierValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public enum IdentifierTypeType
    {
        
        /// <remarks/>
        eori,
        
        /// <remarks/>
        vat,
        
        /// <remarks/>
        cin,
        
        /// <remarks/>
        duns,
        
        /// <remarks/>
        comp_reg,
        
        /// <remarks/>
        comp_num,
        
        /// <remarks/>
        cbr,
        
        /// <remarks/>
        ship_man_comp_imo,
        
        /// <remarks/>
        ship_reg_owner_imo,
        
        /// <remarks/>
        remos,
        
        /// <remarks/>
        gln,
        
        /// <remarks/>
        tin,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public partial class EconomicOperatorIdentificationType
    {
        
        private EconomicOperatorReferenceNumberType[] referenceNumberField;
        
        private NameAndAddressType nameAndAddressField;
        
        private string emailField;
        
        private string phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referenceNumber", Order=0)]
        public EconomicOperatorReferenceNumberType[] referenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public NameAndAddressType nameAndAddress
        {
            get
            {
                return this.nameAndAddressField;
            }
            set
            {
                this.nameAndAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public partial class DueDiligenceStatementBaseType
    {
        
        private string internalReferenceNumberField;
        
        private ActivityType activityTypeField;
        
        private EconomicOperatorIdentificationType operatorField;
        
        private CountryType countryOfActivityField;
        
        private bool countryOfActivityFieldSpecified;
        
        private CountryType borderCrossCountryField;
        
        private bool borderCrossCountryFieldSpecified;
        
        private string commentField;
        
        private CommodityType[] commoditiesField;
        
        private bool geoLocationConfidentialField;
        
        private AssociatedStatementsType[] associatedStatementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string internalReferenceNumber
        {
            get
            {
                return this.internalReferenceNumberField;
            }
            set
            {
                this.internalReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ActivityType activityType
        {
            get
            {
                return this.activityTypeField;
            }
            set
            {
                this.activityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public EconomicOperatorIdentificationType @operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public CountryType countryOfActivity
        {
            get
            {
                return this.countryOfActivityField;
            }
            set
            {
                this.countryOfActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countryOfActivitySpecified
        {
            get
            {
                return this.countryOfActivityFieldSpecified;
            }
            set
            {
                this.countryOfActivityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public CountryType borderCrossCountry
        {
            get
            {
                return this.borderCrossCountryField;
            }
            set
            {
                this.borderCrossCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool borderCrossCountrySpecified
        {
            get
            {
                return this.borderCrossCountryFieldSpecified;
            }
            set
            {
                this.borderCrossCountryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("commodities", Order=6)]
        public CommodityType[] commodities
        {
            get
            {
                return this.commoditiesField;
            }
            set
            {
                this.commoditiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool geoLocationConfidential
        {
            get
            {
                return this.geoLocationConfidentialField;
            }
            set
            {
                this.geoLocationConfidentialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("associatedStatements", Order=8)]
        public AssociatedStatementsType[] associatedStatements
        {
            get
            {
                return this.associatedStatementsField;
            }
            set
            {
                this.associatedStatementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public enum ActivityType
    {
        
        /// <remarks/>
        DOMESTIC,
        
        /// <remarks/>
        TRADE,
        
        /// <remarks/>
        IMPORT,
        
        /// <remarks/>
        EXPORT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public enum CountryType
    {
        
        /// <remarks/>
        AT,
        
        /// <remarks/>
        BE,
        
        /// <remarks/>
        BG,
        
        /// <remarks/>
        CY,
        
        /// <remarks/>
        CZ,
        
        /// <remarks/>
        DE,
        
        /// <remarks/>
        DK,
        
        /// <remarks/>
        EE,
        
        /// <remarks/>
        ES,
        
        /// <remarks/>
        FI,
        
        /// <remarks/>
        FR,
        
        /// <remarks/>
        GR,
        
        /// <remarks/>
        HR,
        
        /// <remarks/>
        HU,
        
        /// <remarks/>
        IE,
        
        /// <remarks/>
        IT,
        
        /// <remarks/>
        LT,
        
        /// <remarks/>
        LU,
        
        /// <remarks/>
        LV,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        NL,
        
        /// <remarks/>
        PL,
        
        /// <remarks/>
        PT,
        
        /// <remarks/>
        RO,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        SI,
        
        /// <remarks/>
        SK,
        
        /// <remarks/>
        XI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/submission/v1")]
    public partial class SubmitStatementRequestType
    {
        
        private OperatorActivityType operatorTypeField;
        
        private DueDiligenceStatementBaseType statementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OperatorActivityType operatorType
        {
            get
            {
                return this.operatorTypeField;
            }
            set
            {
                this.operatorTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DueDiligenceStatementBaseType statement
        {
            get
            {
                return this.statementField;
            }
            set
            {
                this.statementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/model/v1")]
    public enum OperatorActivityType
    {
        
        /// <remarks/>
        OPERATOR,
        
        /// <remarks/>
        TRADER,
        
        /// <remarks/>
        REPRESENTATIVE_OPERATOR,
        
        /// <remarks/>
        REPRESENTATIVE_TRADER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/error/v01")]
    public partial class InvalidParametersExceptionType : ErrorBasedExceptionType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/error/v01")]
    public partial class PermissionDeniedExceptionType : ErrorBasedExceptionType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/error/v01")]
    public partial class CertificatePermissionDeniedExceptionType : ErrorBasedExceptionType
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/submission/v1", ConfigurationName="Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.EUDRSubmissio" +
        "nPort")]
    public interface EUDRSubmissionPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ec.europa.eu/tracesnt/certificate/eudr/submission/submitDds", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.BusinessRulesValidationExceptionType), Action="http://ec.europa.eu/tracesnt/certificate/eudr/submission/submitDds", Name="BusinessRulesValidationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.CertificatePermissionDeniedExceptionType), Action="http://ec.europa.eu/tracesnt/certificate/eudr/submission/submitDds", Name="DdsPermissionDeniedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Error[]))]
        System.Threading.Tasks.Task<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.SubmitStatementResponse> submitDdsAsync(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.SubmitStatementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ec.europa.eu/tracesnt/certificate/eudr/submission/amendDds", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.BusinessRulesValidationExceptionType), Action="http://ec.europa.eu/tracesnt/certificate/eudr/submission/amendDds", Name="BusinessRulesValidationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.CertificatePermissionDeniedExceptionType), Action="http://ec.europa.eu/tracesnt/certificate/eudr/submission/amendDds", Name="DdsPermissionDeniedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Error[]))]
        System.Threading.Tasks.Task<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.AmendStatementResponse> amendDdsAsync(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.AmendStatementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ec.europa.eu/tracesnt/certificate/eudr/submission/retractDds", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.BusinessRulesValidationExceptionType), Action="http://ec.europa.eu/tracesnt/certificate/eudr/submission/retractDds", Name="BusinessRulesValidationException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.CertificatePermissionDeniedExceptionType), Action="http://ec.europa.eu/tracesnt/certificate/eudr/submission/retractDds", Name="DdsPermissionDeniedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Error[]))]
        System.Threading.Tasks.Task<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.RetractStatementResponse> retractDdsAsync(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.RetractStatementRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitStatementRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/base/v4")]
        public string WebServiceClientId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitStatementRequest", Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/submission/v1", Order=0)]
        public Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.SubmitStatementRequestType SubmitStatementRequest1;
        
        public SubmitStatementRequest()
        {
        }
        
        public SubmitStatementRequest(string WebServiceClientId, Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.SubmitStatementRequestType SubmitStatementRequest1)
        {
            this.WebServiceClientId = WebServiceClientId;
            this.SubmitStatementRequest1 = SubmitStatementRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitStatementResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitStatementResponse", Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/submission/v1", Order=0)]
        public Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.SubmitStatementResponseType SubmitStatementResponse1;
        
        public SubmitStatementResponse()
        {
        }
        
        public SubmitStatementResponse(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.SubmitStatementResponseType SubmitStatementResponse1)
        {
            this.SubmitStatementResponse1 = SubmitStatementResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/submission/v1")]
    public partial class AmendStatementRequestType
    {
        
        private string ddsIdentifierField;
        
        private DueDiligenceStatementBaseType statementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ddsIdentifier
        {
            get
            {
                return this.ddsIdentifierField;
            }
            set
            {
                this.ddsIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DueDiligenceStatementBaseType statement
        {
            get
            {
                return this.statementField;
            }
            set
            {
                this.statementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/submission/v1")]
    public partial class StatementModificationResponseType
    {
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AmendStatementRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/base/v4")]
        public string WebServiceClientId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AmendStatementRequest", Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/submission/v1", Order=0)]
        public Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.AmendStatementRequestType AmendStatementRequest1;
        
        public AmendStatementRequest()
        {
        }
        
        public AmendStatementRequest(string WebServiceClientId, Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.AmendStatementRequestType AmendStatementRequest1)
        {
            this.WebServiceClientId = WebServiceClientId;
            this.AmendStatementRequest1 = AmendStatementRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AmendStatementResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AmendStatementResponse", Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/submission/v1", Order=0)]
        public Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.StatementModificationResponseType AmendStatementResponse1;
        
        public AmendStatementResponse()
        {
        }
        
        public AmendStatementResponse(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.StatementModificationResponseType AmendStatementResponse1)
        {
            this.AmendStatementResponse1 = AmendStatementResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/submission/v1")]
    public partial class RetractStatementRequestType
    {
        
        private string ddsIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ddsIdentifier
        {
            get
            {
                return this.ddsIdentifierField;
            }
            set
            {
                this.ddsIdentifierField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetractStatementRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ec.europa.eu/sanco/tracesnt/base/v4")]
        public string WebServiceClientId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetractStatementRequest", Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/submission/v1", Order=0)]
        public Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.RetractStatementRequestType RetractStatementRequest1;
        
        public RetractStatementRequest()
        {
        }
        
        public RetractStatementRequest(string WebServiceClientId, Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.RetractStatementRequestType RetractStatementRequest1)
        {
            this.WebServiceClientId = WebServiceClientId;
            this.RetractStatementRequest1 = RetractStatementRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetractStatementResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetractStatementResponse", Namespace="http://ec.europa.eu/tracesnt/certificate/eudr/submission/v1", Order=0)]
        public Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.StatementModificationResponseType RetractStatementResponse1;
        
        public RetractStatementResponse()
        {
        }
        
        public RetractStatementResponse(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.StatementModificationResponseType RetractStatementResponse1)
        {
            this.RetractStatementResponse1 = RetractStatementResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface EUDRSubmissionPortChannel : Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.EUDRSubmissionPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class EUDRSubmissionPortClient : System.ServiceModel.ClientBase<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.EUDRSubmissionPort>, Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.EUDRSubmissionPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EUDRSubmissionPortClient() : 
                base(EUDRSubmissionPortClient.GetDefaultBinding(), EUDRSubmissionPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.EUDRSubmissionServiceV1Endpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EUDRSubmissionPortClient(EndpointConfiguration endpointConfiguration) : 
                base(EUDRSubmissionPortClient.GetBindingForEndpoint(endpointConfiguration), EUDRSubmissionPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EUDRSubmissionPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EUDRSubmissionPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EUDRSubmissionPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EUDRSubmissionPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EUDRSubmissionPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.SubmitStatementResponse> Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.EUDRSubmissionPort.submitDdsAsync(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.SubmitStatementRequest request)
        {
            return base.Channel.submitDdsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.SubmitStatementResponse> submitDdsAsync(string WebServiceClientId, Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.SubmitStatementRequestType SubmitStatementRequest1)
        {
            Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.SubmitStatementRequest inValue = new Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.SubmitStatementRequest();
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.SubmitStatementRequest1 = SubmitStatementRequest1;
            return ((Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.EUDRSubmissionPort)(this)).submitDdsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.AmendStatementResponse> Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.EUDRSubmissionPort.amendDdsAsync(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.AmendStatementRequest request)
        {
            return base.Channel.amendDdsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.AmendStatementResponse> amendDdsAsync(string WebServiceClientId, Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.AmendStatementRequestType AmendStatementRequest1)
        {
            Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.AmendStatementRequest inValue = new Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.AmendStatementRequest();
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.AmendStatementRequest1 = AmendStatementRequest1;
            return ((Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.EUDRSubmissionPort)(this)).amendDdsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.RetractStatementResponse> Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.EUDRSubmissionPort.retractDdsAsync(Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.RetractStatementRequest request)
        {
            return base.Channel.retractDdsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.RetractStatementResponse> retractDdsAsync(string WebServiceClientId, Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.RetractStatementRequestType RetractStatementRequest1)
        {
            Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.RetractStatementRequest inValue = new Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.RetractStatementRequest();
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.RetractStatementRequest1 = RetractStatementRequest1;
            return ((Eudr.Traces.Integrations.ServiceAgents.Proxys.EUDRSubmissionService.EUDRSubmissionPort)(this)).retractDdsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EUDRSubmissionServiceV1Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EUDRSubmissionServiceV1Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://acceptance.eudr.webcloud.ec.europa.eu/tracesnt/ws/EUDRSubmissionServiceV1" +
                        "");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EUDRSubmissionPortClient.GetBindingForEndpoint(EndpointConfiguration.EUDRSubmissionServiceV1Endpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EUDRSubmissionPortClient.GetEndpointAddress(EndpointConfiguration.EUDRSubmissionServiceV1Endpoint);
        }
        
        public enum EndpointConfiguration
        {
            
            EUDRSubmissionServiceV1Endpoint,
        }
    }
}
